import React from 'react'
import Axios from '../../components/Axios/Axios'

export default function Home() {
  return (
    <div style={{padding:"33px", marginTop:"60px"}}>
     <h1>E-Commercers</h1>
     <p style={{padding:"6px"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem facere architecto, neque omnis labore nemo reiciendis error quisquam veritatis fugiat voluptas, velit provident excepturi corrupti porro voluptates vero nostrum exercitationem! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum quod cum tempora sit error dolorem doloremque illo esse numquam debitis pariatur accusamus, ipsum harum alias aliquid architecto itaque nesciunt mollitia laboriosam incidunt culpa saepe iste. Laboriosam sit alias rerum illo illum vero rem nam ipsum quam beatae consequatur quae, officiis dolore, dignissimos pariatur accusamus fugiat animi. Vero placeat necessitatibus provident cupiditate aut soluta animi quod sequi perferendis architecto, laborum voluptatibus deleniti expedita maxime. Nisi, hic? Ab, dicta fugit! Porro dolores obcaecati corporis aliquid explicabo minus ipsam quibusdam ea sed accusamus, natus facilis voluptatum? Repellendus dolore rem numquam aperiam neque deleniti esse temporibus, vero voluptatem voluptatum quos alias cupiditate nemo molestiae nisi asperiores praesentium quam incidunt? Perspiciatis necessitatibus beatae consequatur laudantium quae, esse odit enim debitis reiciendis aliquid sed dolor. Dolores dolor assumenda, quod consequatur ex porro repellendus veritatis quam repellat odio magni culpa error est unde aut doloribus quo suscipit debitis et sequi nulla! Facilis nihil placeat fuga inventore eaque! Dignissimos, totam deleniti! Optio laudantium obcaecati quidem non deserunt sequi veniam aut provident doloremque illo perspiciatis amet harum modi, ratione rerum fugit. Animi accusantium ducimus consequuntur rerum obcaecati impedit doloremque facilis facere est cupiditate? Corrupti placeat voluptatem illum illo cumque, veniam autem dicta. Architecto vitae quis nobis optio dolor dolorem dolore rem illum aspernatur similique tempore possimus reprehenderit debitis repudiandae numquam modi velit id ipsa illo fugiat voluptas, voluptatibus natus accusamus. Voluptas at dolores laudantium quisquam quae soluta nobis error sint voluptate officiis, eos voluptatem, earum eaque, vel porro provident et a quo doloribus! Porro, ipsa sunt beatae ea et asperiores veritatis. Delectus alias exercitationem beatae non. Voluptatum autem veritatis, earum dicta cumque similique qui, voluptate error odio debitis neque! Quas minima, laudantium asperiores ipsam ipsum blanditiis! Vitae voluptates tempora repellendus mollitia corporis aspernatur asperiores? Facere, voluptatibus voluptate. Ut, illum!</p>
     <h2 style={{padding:"12px"}}>About Products</h2>
     <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloremque repellendus quo quisquam saepe esse? Neque quaerat quo libero modi! Eligendi magni rerum in. Dolor, nostrum voluptas nobis illum beatae, pariatur velit deleniti amet quisquam, natus corporis blanditiis dicta explicabo nihil eveniet! Expedita nemo tempora assumenda doloremque incidunt. Numquam consectetur consequatur error odit delectus magnam quaerat, ipsum cumque doloribus quo reprehenderit officiis pariatur! Quibusdam aut minima qui. Tempore sint deserunt modi dolore dolorum voluptatibus veritatis similique consequatur distinctio saepe! Ex ipsum facere quas aliquam exercitationem aperiam at et obcaecati quasi perferendis voluptates corporis, reprehenderit, provident accusantium dolorem modi atque. Sed, aliquam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores ducimus nulla ab repellat, dolore nisi beatae officia! Provident quis corporis voluptatum rerum error ullam aut modi numquam eaque. Ut odit sint commodi, corrupti officiis sunt itaque assumenda deleniti sed, est nihil. Reprehenderit eveniet placeat, ut blanditiis dolores magni nostrum praesentium voluptatibus impedit dolorem eaque iusto fugit neque ea nemo expedita itaque, similique nihil voluptatum debitis voluptates. Soluta optio sequi voluptate, culpa libero, suscipit magni esse autem minima cum facere quod.</p>
    </div>
  )
}
